version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:THD111@database/student_db"  
    command: ["./wait-for-it.sh", "database:5432", "--", "python", "main.py"]  
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh  # Mount wait-for-it script into the backend service
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: THD111
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
