name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: docker login ecristudenthubregistry.azurecr.io -u ecristudenthubregistry -p ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t ecristudenthubregistry.azurecr.io/frontend:latest .
          docker push ecristudenthubregistry.azurecr.io/frontend:latest

      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ecristudenthubregistry.azurecr.io/backend:latest .
          docker push ecristudenthubregistry.azurecr.io/backend:latest

      - name: Update Docker Compose file
        run: |
          sed -i "s|image:.*backend.*|image: ecristudenthubregistry.azurecr.io/backend:latest|g" docker-compose.yml
          sed -i "s|image:.*frontend.*|image: ecristudenthubregistry.azurecr.io/frontend:latest|g" docker-compose.yml

      - name: Deploy Docker Compose
        run: |
          docker-compose up -d
