name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

      - name: Update Docker Compose file
        run: |
          sed -i "s|image:.*backend.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest|g" docker-compose.yml
          sed -i "s|image:.*frontend.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest|g" docker-compose.yml

      - name: Deploy Docker Compose
        run: |
          docker-compose up -d
